hash-format = "sha256"

[[files]]
file = "config/yosbr/config/bluemap/core.conf"

[[files]]
file = "config/yosbr/config/minelp.json"

[[files]]
file = "config/yosbr/config/polymer/auto-host.json"

[[files]]
file = "config/yosbr/config/polymer/resource-pack.json"

[[files]]
file = "mods/additional-structures.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/armorstandeditor.pw.toml"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
metafile = true

[[files]]
file = "mods/baby-fat-polymer.pw.toml"
metafile = true

[[files]]
file = "mods/blahaj-polymerized.pw.toml"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/borukva-food.pw.toml"
metafile = true

[[files]]
file = "mods/brewery.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/camera-obscura.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/cpmsvcc.pw.toml"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
metafile = true

[[files]]
file = "mods/extended-drawers-polymer.pw.toml"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/filament.pw.toml"
metafile = true

[[files]]
file = "mods/fuji.pw.toml"
metafile = true

[[files]]
file = "mods/glide-away.pw.toml"
metafile = true

[[files]]
file = "mods/goml-reserved.pw.toml"
metafile = true

[[files]]
file = "mods/hd-skins.pw.toml"
metafile = true

[[files]]
file = "mods/illager-expansion-polymer.pw.toml"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/jline4mcdsrv.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
metafile = true

[[files]]
file = "mods/mo-structures.pw.toml"
metafile = true

[[files]]
file = "mods/more-tools.pw.toml"
metafile = true

[[files]]
file = "mods/morefurnaces.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/polydecorations.pw.toml"
metafile = true

[[files]]
file = "mods/polyfactory.pw.toml"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
metafile = true

[[files]]
file = "mods/roguelikedungeons.pw.toml"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
metafile = true

[[files]]
file = "mods/serverbacksnow.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/sit!.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/sswaystones.pw.toml"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/televator.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/toms-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets-polymer.pw.toml"
metafile = true

[[files]]
file = "mods/tsa-concrete.pw.toml"
metafile = true

[[files]]
file = "mods/tsa-decorations.pw.toml"
metafile = true

[[files]]
file = "mods/tsa-planks.pw.toml"
metafile = true

[[files]]
file = "mods/tsa-stone.pw.toml"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
metafile = true

[[files]]
file = "mods/universal-shops.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "resources/resourcepack/required/sparkles.pw.toml"
metafile = true
