name = "Nyx Vanilla"
author = "Sky Splash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
datapack-folder = "./resources/datapack/required/"
no-internal-hashes = true
